FROM golang:1.11 as builder

RUN apt update; apt install -y git

WORKDIR /go/src/istio.io/istio

RUN git clone -b maistra-1.0.0 https://github.com/maistra/istio.git .

RUN make mixs

FROM registry.access.redhat.com/ubi8/ubi-minimal:latest

LABEL com.redhat.component="maistra-mixer-container"
LABEL name="maistra/mixer-ubi8"
LABEL version="1.0.0"
LABEL istion_version="1.1.11"
LABEL summary="Red Hat Istio Mixer OpenShift container image"
LABEL description="Red Hat Istio Mixer OpenShift container image"
LABEL io.k8s.display-name="Red Hat Istio Mixer"
LABEL io.openshift.tags="istio"
LABEL maintainer="Istio Feedback <istio-feedback@redhat.com>"
LABEL io.openshift.expose-services=""
ENV container="oci"
ENV ISTIO_VERSION=1.1.11

COPY --from=builder /go/out/linux_ppc64le/release/mixs /usr/local/bin/mixs

WORKDIR /tmp/

ENTRYPOINT ["/usr/local/bin/mixs", "server"]
CMD ["--configStoreURL=fs:///etc/opt/mixer/configroot","--configStoreURL=k8s://"]
